unit DS.Server.Model.Entity.Pessoa.Consts;

interface

const
  SQL_PESSOA_GET = 'SELECT * FROM PESSOA ORDER BY IDPESSOA DESC';
  SQL_PESSOA_GET_WHERE = 'SELECT * FROM PESSOA WHERE IDPESSOA = :ID';
  SQL_PESSOA_POST = 'SELECT * FROM PESSOA WHERE IDPESSOA = :ID';
  SQL_PESSOA_PUT = 'SELECT * FROM PESSOA WHERE 1=2';
  SQL_PESSOA_DELETE = 'DELETE FROM PESSOA WHERE IDPESSOA = :ID';
  CONST_PARAMETER_ID = 'ID';
  CONST_PARAMETER_APPLY_UPDATE = -1;

implementation

end.
